### ISSUE TITLE
batch_size issue

### ISSUE THREAD

**Issue by No-zim** [keras-team/keras#11826]
When I run this code (directly from a book)
Keras version 2.2.4 (Tensorflow Backend)
cuda 9
cuDNN

everything is alright until I try to fit reshaped input into a network:
network.fit(train_i, train_l, epochs=5, batch_size=64)
--------------------------------------------------------------------------------------------------------------
**this is the code I am trying to run:**
from keras import layers
from keras import models
from keras.datasets import mnist
from keras.utils import to_categorical

network =models.Sequential()
network.add(layers.Conv2D(32,(3,3), activation='relu', input_shape =(28,28,1)))
network.add(layers.MaxPooling2D((2,2)))
network.add(layers.Conv2D(64,(3,3), activation='relu'))
network.add(layers.MaxPooling2D((2,2)))
network.add(layers.Conv2D(64,(3,3), activation='relu'))
network.add(layers.Flatten())
network.add(layers.Dense(64, activation='relu'))
network.add(layers.Dense(10,activation='softmax'))

(train_i, train_l), (test_i, test_l) =mnist.load_data()

train_i =train_i.reshape((60000,28,28,1))
train_i =train_i.astype('float32')/255

test_i =test_i.reshape((10000,28,28,1))
test_i =test_i.astype('float32')/255
train_l =to_categorical(train_l)
test_l =to_categorical(test_l)

network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])
network.fit(train_i, train_l, epochs=5, batch_size=64)

test_loss, test_acc =network.evaluate(test_i,test_l)
print(test_acc)
----------------------------------------------------------------------------------------------------------
**### Error when I run it on Jupyter:**

ValueError                                Traceback (most recent call last)
<ipython-input-29-1192ff6bb6e6> in <module>()
----> 1 network.fit(train_i, train_l, epochs=5, batch_size=64)

C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    950             sample_weight=sample_weight,
    951             class_weight=class_weight,
--> 952             batch_size=batch_size)
    953         # Prepare validation data.
    954         do_validation = False

C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    787                 feed_output_shapes,
    788                 check_batch_axis=False,  # Don't enforce the batch size.
--> 789                 exception_prefix='target')
    790 
    791             # Generate sample-wise weight values given the `sample_weight` and

C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    126                         ': expected ' + names[i] + ' to have ' +
    127                         str(len(shape)) + ' dimensions, but got array '
--> 128                         'with shape ' + str(data_shape))
    129                 if not check_batch_axis:
    130                     data_shape = data_shape[1:]

ValueError: Error when checking target: expected dense_2 to have 2 dimensions, but got array with shape (60000, 10, 2, 2, 2, 2, 2)

-----------------------------------------------------------------------------------------------------------
**### Error on regular Pycharm python file:**

Using TensorFlow backend.
Epoch 1/5
2018-12-08 22:31:16.754288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-12-08 22:31:16.754724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-08 22:31:16.755126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-12-08 22:31:16.755388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-12-08 22:31:16.755764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6353 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:07:00.0, compute capability: 6.1)
2018-12-08 22:31:17.939193: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-12-08 22:31:17.939849: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-12-08 22:31:17.944357: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-12-08 22:31:17.944929: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-12-08 22:31:17.945695: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-12-08 22:31:17.946336: E tensorflow/stream_executor/cuda/cuda_blas.cc:464] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2018-12-08 22:31:22.799483: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2018-12-08 22:31:22.801824: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "C:/Users/****/PycharmProjects/KerasFirstCNN/omg.py", line 43, in <module>
    network.fit(train_i, train_l, epochs=5, batch_size=64)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\****\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@training/RMSprop/gradients/conv2d_1/convolution_grad/Conv2DBackpropFilter"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/RMSprop/gradients/conv2d_1/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/kernel/read)]]
	 [[{{node metrics/acc/Mean/_85}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_621_metrics/acc/Mean", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by No-zim** [comment]
It was confusing input names

**Comment by No-zim** [comment]
how do you delete these posts

**Comment by No-zim** [comment]
Still this issue, any suggestions?

**Comment by No-zim** [comment]
and I'm using tensorflow-gpu 1.12.0

**Comment by tynefung** [comment]
Same issue, waiting for help!

**Comment by No-zim** [comment]
As some say: help will always be given at github to those who deserve it. It seems we don't deserve it

**Comment by Golbstein** [comment]
I copy pasted this code and I'm using Keras 2.2.4 and it works fine for me.. try to restart the kernel.. your error throws something about the sample_weights but you don't specify anywhere the sample_weights so are you sure you copy-pasted the full version here?
