### ISSUE TITLE
Error selecting GPU programmatically from jupyter

### ISSUE THREAD

**Issue by lminer** [keras-team/keras#12393]
I have a multi-GPU machine and am trying to train different models on different GPUs. I'm trying to set the GPU programmatically rather than use env vars, but am running into issues. Here's my code:

```python
def choose_gpu(gpu_id):
    os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
    with K.tf.device(f'/gpu:{gpu_id}'):
        config = tf.ConfigProto(intra_op_parallelism_threads=10,
                                inter_op_parallelism_threads=10,
                                allow_soft_placement=True,
                                device_count={'CPU': 1, 'GPU': 1})
        session = tf.Session(config=config)
        K.set_session(session)
```

However, when I try to run the code in two separate jupyter notebooks, using ids 0 and 1, I get the following error:

```
2019-03-04 10:36:27.210489: W tensorflow/compiler/xla/service/platform_util.cc:240] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 11523260416
2019-03-04 10:36:27.210803: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56311c4bccf0 executing computations on platform CUDA. Devices:
2019-03-04 10:36:27.211230: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value
instead of handling error Invalid argument: device CUDA:0 not supported by XLA service
```

It works fine if I set `CUDA_VISIBLE_DEVICES` at the top of the script, but I'd rather not have to manage this. Any sense of what I may be doing wrong? I'm using
- keras 2.2.4
- tensorflow 1.13.1
- ubuntu 18.04
- jupyter 5.2.4
- jupyter lab 0.35.4

**Comment by Tiaspetto** [comment]
environment param need to be set before you import keras

**Comment by lminer** [comment]
Even when I do that, one of the instances crashes at the end of the first epoch. I don't even get any error message. Just a message that the kernel was reset.

**Comment by ymodak** [comment]
@lminer  Is this still an issue for you? I have cross posted this issue on TF repo  as well for TF folks to take a look. Here is the [link](https://github.com/tensorflow/tensorflow/issues/27122) to it. Thanks!

**Comment by lminer** [comment]
@ymodak I think I solved the problem. Kernel reset was a different issue.

**Comment by ymodak** [comment]
Cool. I will go ahead and close this issue now. Thanks!

**Comment by Przemek-T** [comment]
@lminer and @ymodak what was the solution to this problem ?

**Comment by srkm009** [comment]
@lminer How did you manage to solve this issue?

**Comment by mave240** [comment]
I have four GPUs on my machine (Ubuntu 1804).

Setting:

`export CUDA_VISIBLE_DEVICES=0,1,2,3`

in the shell, or

```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3'
```

worked for me.
