### ISSUE TITLE
memory leak following `model.fit()` for tf 2.7, 2.8, 2.9 (nightly), works fine for 2.5

### ISSUE THREAD

**Issue by alternativebug** [keras-team/keras#16019]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code: custom code
- OS Platform and Distribution: Ubuntu 18 (google colab)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7, 2.8, 2.9.0-dev20220203
- Python version: 3.7, 3.9, 3.10
- CUDA/cuDNN version: Build cuda_11.1.TC455_06.29190527_0
- GPU model and memory: varies

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I'm using my yolo [implementation](https://github.com/alternativebug/yolo-tf2) which used to work fine on tensorflow versions prior to 2.5. I tried recently training yolo3 on a small dataset (which uses `tf.keras.Model.fit`). Here's a colab [notebook](https://colab.research.google.com/drive/18jCTQajjgBO2bmKekaI5frrluJ2CX4NN?usp=sharing) which you can use to reproduce the issue. Shortly after `model.fit` is called, the following 2 messages keep repeating in no particular order:

    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)

and

    INFO:tensorflow:Assets written to: ram://eefa3127-ad7d-4445-a186-75fd8f0b81e1/assets

They keep repeating, memory usage keeps growing and eventually a memory crash occurs. (which doesn't happen in earlier tensorflow versions <= 2.5). You can verify so using this other [notebook](https://colab.research.google.com/drive/1a3RAhVA3pCTQj2FyGY2df7vum27pj69a?usp=sharing) which uses tensorflow 2.5 instead, things should go perfectly fine and training goes as expected. I also tried installing tensorflow 2.8 instead of colab's default version (2.7) and the issue persists.

**Describe the expected behavior**

I'm expecting to see the following immediately after `model.fit` is called:

    Epoch 1/100

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): yes with enough info
- Briefly describe your candidate solution(if contributing): will describe one when I have one.

**Standalone code to reproduce the issue**
* [Notebook](https://colab.research.google.com/drive/18jCTQajjgBO2bmKekaI5frrluJ2CX4NN?usp=sharing) with error
* [Notebook](https://colab.research.google.com/drive/1a3RAhVA3pCTQj2FyGY2df7vum27pj69a?usp=sharing) without error

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Here's the output containing problems (notebook 1):

    2022-02-07 05:52:00,476 yolo_tf2.utils.common.activate_gpu +325: INFO     [260] GPU activated
    2022-02-07 05:52:00,477 yolo_tf2.utils.common.train +468: INFO     [260] Starting training ...
    2022-02-07 05:52:04,293 yolo_tf2.utils.common.create_models +447: INFO     [260] Training and inference models created
    2022-02-07 05:52:04,295 yolo_tf2.utils.common.wrapper +64: INFO     [260] create_models execution time: 3.8118433569999866 seconds
    2022-02-07 05:52:04,301 yolo_tf2.utils.common.create_new_dataset +366: INFO     [260] Generating new dataset ...
    2022-02-07 05:52:07,014 yolo_tf2.utils.common.adjust_non_voc_csv +184: INFO     [260] Adjustment from existing received 10107 labels containing 16 classes
    2022-02-07 05:52:07,022 yolo_tf2.utils.common.adjust_non_voc_csv +187: INFO     [260] Added prefix to images: /content/yolo-data/images
    Parsed labels:
    Car               3153
    Pedestrian        1418
    Palm Tree         1379
    Traffic Lights    1269
    Street Sign       1109
    Street Lamp        995
    Road Block         363
    Flag               124
    Trash Can           90
    Minivan             68
    Fire Hydrant        52
    Bus                 43
    Pickup Truck        20
    Bicycle             17
    Delivery Truck       4
    Motorcycle           3
    Name: object_name, dtype: int64
    2022-02-07 05:52:09,513 yolo_tf2.utils.common.save_fig +33: INFO     [260] Saved figure /content/output/plots/Relative width and height for 10107 boxes..png
    /usr/local/lib/python3.7/dist-packages/yolo_tf2/utils/dataset_handlers.py:209: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
      groups = np.array(data.groupby('image_path'))
    Processing beverly_hills_train.tfrecord
    Building example: 406/411 ... Beverly_hills184.jpg 99% completed2022-02-07 05:52:12,922 yolo_tf2.utils.common.save_tfr +227: INFO     [260] Saved training TFRecord: /content/data/tfrecords/beverly_hills_train.tfrecord
    Building example: 411/411 ... Beverly_hills365.jpg 100% completed
    Processing beverly_hills_test.tfrecord
    Building example: 31/46 ... Beverly_hills335.jpg 67% completed2022-02-07 05:52:13,175 yolo_tf2.utils.common.save_tfr +229: INFO     [260] Saved validation TFRecord: /content/data/tfrecords/beverly_hills_test.tfrecord
    2022-02-07 05:52:13,271 yolo_tf2.utils.common.read_tfr +263: INFO     [260] Read TFRecord: /content/data/tfrecords/beverly_hills_train.tfrecord
    Building example: 46/46 ... Beverly_hills186.jpg 100% completed
    2022-02-07 05:52:18,892 yolo_tf2.utils.common.read_tfr +263: INFO     [260] Read TFRecord: /content/data/tfrecords/beverly_hills_test.tfrecord
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    2022-02-07 05:52:50.575910: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
    INFO:tensorflow:Assets written to: ram://eefa3127-ad7d-4445-a186-75fd8f0b81e1/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://cbe6d5a4-5322-494b-ba91-3fd34131cdd9/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://f15f3f25-9adb-4eb0-aa0d-83fa874bc74e/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://86dd6f5f-4416-4465-99c0-928fd88e8a93/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://ca08220f-cabc-4017-96d3-383557342388/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://0f634207-e822-4d6c-a805-3cfeab37532f/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://a971d021-3da4-402a-a004-4ae4aa67148a/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://31d72fdf-1ce6-4131-a7e6-f6444747e9c9/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://dac323b6-591a-481c-bbe6-85bb82bef38c/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://99b029f7-11d1-40f2-b459-fd1d8dca5ba1/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)
    INFO:tensorflow:Assets written to: ram://210489fb-0895-4769-8be3-effd01d92695/assets
    /usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      layer_config = serialize_layer_fn(layer)

Here's the output without the problem (notebook 2):

    2022-02-07 06:09:53.125735: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
    2022-02-07 06:09:55.370728: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
    2022-02-07 06:09:55,387 yolo_tf2.utils.common.train +468: INFO     [269] Starting training ...
    2022-02-07 06:09:55.387211: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
    2022-02-07 06:09:55.387252: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (de0312867ce7): /proc/driver/nvidia/version does not exist
    2022-02-07 06:09:55.427963: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
    To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
    2022-02-07 06:10:00,078 yolo_tf2.utils.common.create_models +447: INFO     [269] Training and inference models created
    2022-02-07 06:10:00,080 yolo_tf2.utils.common.wrapper +64: INFO     [269] create_models execution time: 4.689235652999997 seconds
    2022-02-07 06:10:00,081 yolo_tf2.utils.common.create_new_dataset +366: INFO     [269] Generating new dataset ...
    2022-02-07 06:10:02,572 yolo_tf2.utils.common.adjust_non_voc_csv +184: INFO     [269] Adjustment from existing received 10107 labels containing 16 classes
    2022-02-07 06:10:02,574 yolo_tf2.utils.common.adjust_non_voc_csv +187: INFO     [269] Added prefix to images: /content/yolo-data/images
    Parsed labels:
    Car               3153
    Pedestrian        1418
    Palm Tree         1379
    Traffic Lights    1269
    Street Sign       1109
    Street Lamp        995
    Road Block         363
    Flag               124
    Trash Can           90
    Minivan             68
    Fire Hydrant        52
    Bus                 43
    Pickup Truck        20
    Bicycle             17
    Delivery Truck       4
    Motorcycle           3
    Name: object_name, dtype: int64
    2022-02-07 06:10:04,900 yolo_tf2.utils.common.save_fig +33: INFO     [269] Saved figure /content/output/plots/Relative width and height for 10107 boxes..png
    /usr/local/lib/python3.7/dist-packages/yolo_tf2/utils/dataset_handlers.py:209: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
      groups = np.array(data.groupby('image_path'))
    Processing beverly_hills_train.tfrecord
    Building example: 392/411 ... Beverly_hills294.jpg 95% completed2022-02-07 06:10:10,341 yolo_tf2.utils.common.save_tfr +227: INFO     [269] Saved training TFRecord: /content/data/tfrecords/beverly_hills_train.tfrecord
    Building example: 411/411 ... Beverly_hills94.jpg 100% completed
    Processing beverly_hills_test.tfrecord
    Building example: 25/46 ... Beverly_hills334.jpg 54% completed2022-02-07 06:10:10,730 yolo_tf2.utils.common.save_tfr +229: INFO     [269] Saved validation TFRecord: /content/data/tfrecords/beverly_hills_test.tfrecord
    Building example: 46/46 ... Beverly_hills251.jpg 100% completed
    2022-02-07 06:10:10,843 yolo_tf2.utils.common.read_tfr +263: INFO     [269] Read TFRecord: /content/data/tfrecords/beverly_hills_train.tfrecord
    2022-02-07 06:10:15,264 yolo_tf2.utils.common.read_tfr +263: INFO     [269] Read TFRecord: /content/data/tfrecords/beverly_hills_test.tfrecord
    2022-02-07 06:10:15.676352: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
    2022-02-07 06:10:15.676423: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.
    2022-02-07 06:10:15.701051: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session tear down.
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/utils/generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
      category=CustomMaskWarning)
    2022-02-07 06:10:17.064324: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
    2022-02-07 06:10:17.081408: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2199995000 Hz
    Epoch 1/100
          1/Unknown - 40s 40s/step - loss: 7333.2617 - layer_205_lambda_loss: 403.8862 - layer_230_lambda_loss: 1509.9465 - layer_255_lambda_loss: 5407.68902022-02-07 06:10:59.974130: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
    2022-02-07 06:10:59.974196: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.
          2/Unknown - 50s 11s/step - loss: 7819.7124 - layer_205_lambda_loss: 697.4546 - layer_230_lambda_loss: 1647.7856 - layer_255_lambda_loss: 5462.71582022-02-07 06:11:10.059899: I tensorflow/core/profiler/lib/profiler_session.cc:66] Profiler session collecting data.
    2022-02-07 06:11:10.088821: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session tear down.
    2022-02-07 06:11:10.133747: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10
    2022-02-07 06:11:10.157875: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for trace.json.gz to /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10/de0312867ce7.trace.json.gz
    2022-02-07 06:11:10.189438: I tensorflow/core/profiler/rpc/client/save_profile.cc:137] Creating directory: /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10
    2022-02-07 06:11:10.189678: I tensorflow/core/profiler/rpc/client/save_profile.cc:143] Dumped gzipped tool data for memory_profile.json.gz to /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10/de0312867ce7.memory_profile.json.gz
    2022-02-07 06:11:10.192796: I tensorflow/core/profiler/rpc/client/capture_profile.cc:251] Creating directory: /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10Dumped tool data for xplane.pb to /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10/de0312867ce7.xplane.pb
    Dumped tool data for overview_page.pb to /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10/de0312867ce7.overview_page.pb
    Dumped tool data for input_pipeline.pb to /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10/de0312867ce7.input_pipeline.pb
    Dumped tool data for tensorflow_stats.pb to /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10/de0312867ce7.tensorflow_stats.pb
    Dumped tool data for kernel_stats.pb to /content/data/tfrecords/train/plugins/profile/2022_02_07_06_11_10/de0312867ce7.kernel_stats.pb
    
         15/Unknown - 181s 10s/step - loss: 3493.4009 - layer_205_lambda_loss: 232.7220 - layer_230_lambda_loss: 629.6332 - layer_255_lambda_loss: 2618.9722

**Comment by alternativebug** [comment]
I was able to fix the problem by refactoring my code and I'll close this issue since I'm not sure whether it's relevant anymore .

**Comment by NoMansBase** [comment]
What was it in your code that was causing the issue that was solved with refactoring? I'm encountering a similar issue.

**Comment by unsignedrant** [comment]
Perhaps let me look at your code and I'll tell you of similarities if any. I'm not sure what was causing the issue. The code was in a state of disorder and needed refactoring, not sure which was the real reason behind the error.

**Comment by NoMansBase** [comment]
I'm using GradienTape instead of fit because it's a GAN and it's a bit simpler to write the training loop manually instead of trying to create a GAN model that could be fitted.

This is my minimal code btw:
`import numpy as np
import tensorflow as tf
from memory_profiler import profile
from tqdm import tqdm

def smooth_positive_labels(y):
    '''Helper function to introduce some noise
    around the hard 1 labels
    '''
    return y - 0.15 + (np.random.random(y.shape) * 0.25)

def smooth_negative_labels(y):
    '''Helper function to introduce some noise
    around the hard 0 labels
    '''
    return y + np.random.random(y.shape) * 0.15

def noisy_labels(y, p_flip):
    '''Helper function to flip some labels
    to improve robustness of network
    (NOT USED AT THE MOMENT)
    '''
    # determine the number of labels to flip
    n_select = int(p_flip * y.shape[0])
    # choose labels to flip
    flip_ix = np.random.choice([i for i in range(y.shape[0])], size=n_select)
    # invert the labels
    y[flip_ix] = 1 - y[flip_ix]
    return y

def is_empty(tensor):
    return tf.equal(tf.size(tensor), 0)

def extract_unmasked_values(img, mask):
    '''
    Extracts unmasked values from a frame/film/batch.
    ! Returns a flattened tensor
    Returns 0 if either the image or the valid image
    is empty
    '''
    if is_empty(img):
        return tf.constant([0])
    flattened_img = tf.reshape(img, [-1])
    bool_mask = tf.cast(tf.reshape(mask, [-1]), dtype=bool)
    valid_img = tf.boolean_mask(flattened_img, bool_mask)
    if is_empty(valid_img):
        return tf.constant([0])
    return valid_img

class RandomData:

    def __init__(self, batchsize=1, windowsize=128, tslength=16, p=0.2):
        self.windowsize=windowsize
        self.tslength=tslength
        self.p=p
        self.batchsize = batchsize
    
    def get(self):
        s2 = np.random.rand(self.batchsize, self.tslength, self.windowsize, self.windowsize, 1)
        s1 = np.random.rand(self.batchsize, self.tslength, self.windowsize, self.windowsize, 2)
        mask = np.random.choice([1, 0], size=(self.batchsize, self.tslength, self.windowsize, self.windowsize, 1), p=[1-self.p, self.p])
        add_mask = np.random.choice([1, 0], size=(self.batchsize, self.tslength, self.windowsize, self.windowsize, 1), p=[1-self.p, self.p])
        syn_mask = mask * add_mask
        syn_s2 = s2 * syn_mask
        origin_s2 = s2 * mask
        return {
            'original': tf.convert_to_tensor(np.concatenate(
                [origin_s2, mask], axis=-1
            ), dtype=tf.float32),
            'synthetic': tf.convert_to_tensor(np.concatenate(
                [syn_s2, s1, mask], axis=-1
            ), dtype=tf.float32)
        }

class Generator(tf.keras.Model):

    def __init__(self, filters=32, depth=3, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.stack = []
        for i in range(depth):
            self.stack.append(tf.keras.layers.Conv3D(filters, (3,3,3), padding='same'))
            self.stack.append(tf.keras.layers.BatchNormalization())
            self.stack.append(tf.keras.layers.ReLU())
        self.stack.append(tf.keras.layers.Conv3D(1, (3,3,3), padding='same'))
    
    def call(self, inputs):
        x =  inputs
        for i in range(len(self.stack)):
            x = self.stack[i](x)
        return x

class Discriminator(tf.keras.Model):

    def __init__(self, filters=32, depth=3, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.stack = []
        for i in range(depth):
            self.stack.append(tf.keras.layers.Conv3D(filters, (3,3,3), strides=(2,2,2)))
            self.stack.append(tf.keras.layers.BatchNormalization())
            self.stack.append(tf.keras.layers.ReLU())
    
    def call(self, inputs):
        x =  inputs
        for i in range(len(self.stack)):
            x = self.stack[i](x)
        return x

class GAN:

    def __init__(self):
        self.generator = Generator()
        self.gen_optimizer = tf.keras.optimizers.Adam(learning_rate=1E-4)

        self.discriminator = Discriminator()
        self.disc_optimizer = tf.keras.optimizers.Adam(learning_rate=1E-4)

        self.loss = tf.losses.BinaryCrossentropy()
    
    def _discriminator_loss(self, true_output, pred_output):
        ones = smooth_positive_labels(np.ones_like(true_output))
        zeros = smooth_negative_labels(np.zeros_like(pred_output))
        noisy_ones = noisy_labels(ones, 0.1)
        noisy_zeros = noisy_labels(zeros, 0.1)

        real_loss = self.loss(noisy_ones, true_output)
        generated_loss = self.loss(noisy_zeros, pred_output)
        total_disc_loss = tf.add(.5 * real_loss, .5 * generated_loss)

        return total_disc_loss
    
    def _generator_loss(self, true_image, pred_image, true_mask, syn_mask, disc_output):
        true_image_valid = extract_unmasked_values(true_image, true_mask)
        pred_image_valid = extract_unmasked_values(pred_image, true_mask)
        l1_loss = tf.reduce_mean(tf.abs(true_image_valid - pred_image_valid))

        gan_loss = self.loss(tf.ones_like(disc_output), disc_output)
        total_loss = gan_loss + l1_loss
        return total_loss
    
    def _run_step(self, original_inputs, synthetic_inputs, training=False):
        true_image = original_inputs[..., 0:1]
        true_mask = original_inputs[...,1:]
        pred_image = self.generator(synthetic_inputs, training=training)
        syn_mask = synthetic_inputs[...,3:]
        true_output = self.discriminator(true_image, training=training)
        pred_output = self.discriminator(pred_image, training=training)

        gen_loss = self._generator_loss(true_image, pred_image, true_mask, syn_mask, true_output)
        disc_loss = self._discriminator_loss(true_output, pred_output)
        losses = dict(
            gen_loss = gen_loss,
            disc_loss = disc_loss
        )
        return losses
    
    def train_step(self, original_inputs, synthetic_inputs):
        with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
            losses = self._run_step(original_inputs, synthetic_inputs, training=True)

        gradients_of_generator = gen_tape.gradient(
            losses['gen_loss'],
            self.generator.trainable_variables
        )
        gradients_of_discriminator = disc_tape.gradient(
            losses['disc_loss'],
            self.discriminator.trainable_variables
        )

        # Optimize gradients disc -> refined -> coarse
        self.disc_optimizer.apply_gradients(
            zip(gradients_of_discriminator, self.discriminator.trainable_variables)
        )
        self.gen_optimizer.apply_gradients(
            zip(gradients_of_generator, self.generator.trainable_variables)
        )
        return losses

    def test_step(self, original_inputs, synthetic_inputs):
        losses = self._run_step(original_inputs, synthetic_inputs, training=True)
        return losses

class GANTrainer:

    def __init__(self, batchsize=1, windowsize=128, tslength=16):
        self.gan = GAN()
        self.data_generator = RandomData(batchsize=batchsize, windowsize=windowsize, tslength=tslength)
    
    def _train_step(self, epoch, step):
        inputs = self.data_generator.get()
        losses = self.gan.train_step(inputs['original'], inputs['synthetic'])

    @profile
    def _train_epoch(self, epoch):
        for step in tqdm(range(self.num_steps), desc='Training Epoch {}'.format(epoch + 1)):
            losses = self._train_step(epoch, step)
    
    def _validation_step(self, epoch, step):
        inputs = self.data_generator.get()
        losses = self.gan.train_step(inputs['original'], inputs['synthetic'])
        return losses

    @profile
    def _validate_epoch(self, epoch):
        losses = []
        for step in tqdm(range(self.num_val_steps), desc="Running validation for epoch {}...".format(epoch + 1)):
            losses.append(self._validation_step(epoch, step))
        return losses[-1]['gen_loss']
    
    def run(self, num_epochs, num_steps, num_val_steps):
        self.num_steps = num_steps
        self.num_val_steps = num_val_steps
        while True:
            try:
                lowest_val_loss = 1000
                for epoch in range(num_epochs):
                    self._train_epoch(epoch)
                    loss_val = self._validate_epoch(epoch)
            except tf.errors.OutOfRangeError:
                pass
            break

if __name__ == '__main__':
    trainer = GANTrainer(batchsize=64, windowsize=32, tslength=16)
    trainer.run(10, 100, 20)`

**Comment by unsignedrant** [comment]
Regarding the formatting, just select all the code and press tab or wrap it using ```. Regarding the code, what happens when you run it? what versions are you using (tensorflow, python, os, ...)?

**Comment by splendidbug** [comment]
> 

Hey, did you find a solution? Even I'm facing the same issue

**Comment by unsignedrant** [comment]
@NoMansBase You're not using `keras.Model.fit` which makes the problem you're facing irrelevant to the subject of this issue. Besides, your code is running perfectly fine on [colab](https://colab.research.google.com/drive/1AbD1_4jJBa_LTxzj98_EwYnM5bOKDTTA?usp=sharing) and the memory usage is constant over 5 epochs (~= 1.9 GB). Does the remote instance have limited memory (less than 2GB in this case)? If so, try reducing the batch size to 32, 16, ... whichever works.

**Comment by unsignedrant** [comment]
@splendidbug can you include the logs and your code?

**Comment by splendidbug** [comment]
@unsignedrant Hey, I'm new at this and I'm on an NDA so I cannot directly share the code and this is might not be a "memory leak issue". But the problem I'm facing is initially my gpu memory available is 3539 MB. After building the model which is:

Layer (type)                 Output Shape              Param #   
=================================================================
embedding (Embedding)        (None, 600, 768)          23440896  
_________________________________________________________________
bidirectional (Bidirectional (None, 600, 512)          2099200   
_________________________________________________________________
dropout (Dropout)            (None, 600, 512)          0         
_________________________________________________________________
global_max_pooling1d (Global (None, 512)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense (Dense)                (None, 4)                 2052      
=================================================================
Total params: 25,542,148
Trainable params: 2,101,252
Non-trainable params: 23,440,896
_________________________________________________________________
None


The available GPU memory comes down to 3105 MB. After loading a saved model it comes down to 2827 MB. Now if i start training using `history = model2.fit(X, Y, epochs = 20,batch_size = 4, validation_split=0.2, verbose = 1)`  (shape of X_test is (140, 600) and Y_test is (140, 4) which is not a large dataset) the memory drastically drops to 1141 MB which doesn't really leave me room for training if i want to perform with a bit larger dataset, I get an OOM error. OOM also occurs if I start training without explicitly mentioning the batch size (it takes a default of 32 I believe). I tried performing
 `tf.keras.backend.clear_session()
gc.collect()`

but it didn't really help, the available gpu memory remains the same.

**Comment by unsignedrant** [comment]
The memory should not be affected by the dataset size, that's what `batch_size` is for, unless you're loading the full dataset into memory, in which case you have to modify your code to deal with this problem using [generators](https://wiki.python.org/moin/Generators) or [tfrecords](https://www.tensorflow.org/tutorials/load_data/tfrecord). Given this is not a problem, and the dataset is loaded properly, you need to either reduce the batch size or increase the available memory since clearly this is not a memory leaking issue.

**Comment by splendidbug** [comment]
@unsignedrant Alright. Thanks a lot!
