### ISSUE TITLE
DataLoaders & CUDA Errors with torch backend

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras#18592]
Hi, I am trying to use Keras Core (manually installed) with torch backend. I noticed that the PyDataset class is now Sequence. Installing the cuda requeriments for torch, it throws problems as it does not recognize the GPU (all drivers are installed correctly, as using the TF backend in another environment it works correctly). 

Regarding data management with Custom Generators (PyDataset and torch DataLoaders), they are not well managed. 

```
Traceback (most recent call last):
  File "/home/em/PycharmProjects/KerasCoreTemplates/main.py", line 109, in <module>
    model.fit(train_dataloader, validation_data=val_dataloader, epochs=3, verbose=1)
  File "/home/em/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/em/.local/lib/python3.10/site-packages/keras/src/engine/data_adapter.py", line 1105, in select_data_adapter
    raise ValueError(
ValueError: Failed to find data adapter that can handle input: <class 'torch.utils.data.dataloader.DataLoader'>, <class 'NoneType'>

```

Code:

```
import os
# To avoid deadlock in multiprocessing (Keras Core bug)
# Always import first keras
import keras
from keras import layers
if os.environ["KERAS_BACKEND"] is not None and os.environ["KERAS_BACKEND"] == "torch":
    import torch
    from Trainers import TorchModel
    import tensorflow as tf
else:
    import tensorflow as tf
import numpy as np
from pathlib import Path
from Trainers import TensorflowModel, JaxTrainer
from typing import Tuple, Any
from DataUtils import ExampleTorchDataset

SEED = 42  # Set seed for reproducibility

preprocess_seq = keras.Sequential([
    layers.Lambda(lambda x: tf.expand_dims(x, axis=-1)),
    layers.Resizing(28, 28, crop_to_aspect_ratio=True),
    layers.Rescaling(1. / 255),
])


def generate_model(input_shape: Tuple[int, int, int], output_shape: Any, backend: str) -> keras.Model:
    """
    Generate a model based on target backend
    :param input_shape: The input shape of the model
    :param output_shape: The output shape of the model
    :param backend: The backend use for train the model
    :return: The compiled model
    """
    inputs = keras.Input(shape=input_shape + (1,))
    x = layers.Conv2D(filters=64, kernel_size=3, padding='same')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPool2D(pool_size=2, strides=2)(x)
    x = layers.Conv2D(filters=32, kernel_size=3, padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.Flatten()(x)
    outputs = layers.Dense(units=output_shape)(x)

    # Ensemble the model
    if backend == "tensorflow":
        model = TensorflowModel(inputs=inputs, outputs=outputs)
    elif backend == "torch":
        model = TorchModel(inputs=inputs, outputs=outputs)
    elif backend == "jax":
        model = JaxTrainer(inputs=inputs, outputs=outputs)
    else:
        raise ValueError(
            "Unknown backend, please config environment var KERAS_BACKEND. E.g> conda env config vars set KERAS_BACKEND=tensorflow")
    model.compile(optimizer="adam", loss=keras.losses.CategoricalCrossentropy(from_logits=True))
    return model




# (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train = np.memmap('Data/x_train.mmap', dtype='float32', mode='r', shape=(60000, 28, 28))
y_train = np.memmap('Data/y_train.mmap', dtype='int8', mode='r', shape=(60000,))
x_test = np.memmap('Data/x_test.mmap', dtype='float32', mode='r', shape=(10000, 28, 28))
y_test = np.memmap('Data/y_test.mmap', dtype='int8', mode='r', shape=(10000,))

if os.environ["KERAS_BACKEND"] == "torch":
    # train_ds = TrainerPyDataset(x_train, y_train, batch_size=64, num_classes=10, use_multiprocessing=True, workers=4)
    # test_ds = TrainerPyDataset(x_test, y_test, batch_size=64, num_classes=10, use_multiprocessing=True, workers=4)

    train_torch_dataset = ExampleTorchDataset(x_train, y_train)
    val_torch_dataset = ExampleTorchDataset(x_test, y_test)

    train_dataloader = torch.utils.data.DataLoader(
        train_torch_dataset, batch_size=32, shuffle=True
    )
    val_dataloader = torch.utils.data.DataLoader(
        val_torch_dataset, batch_size=32, shuffle=True
    )
else:
    # Torch backend doesn't support tf.data.Dataset which uses a Keras Model for preprocessing inside map function
    train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)) \
        .map(lambda x, y: (preprocess_seq(x), keras.utils.to_categorical(y, num_classes=10))) \
        .batch(32)\
        .shuffle(buffer_size=8)\
        .prefetch(tf.data.AUTOTUNE)

    test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)) \
        .map(lambda x, y: (preprocess_seq(x), keras.utils.to_categorical(y, num_classes=10))) \
        .batch(32)\
        .shuffle(buffer_size=8)\
        .prefetch(tf.data.AUTOTUNE)

models_dir = Path("Models")

if not models_dir.exists():
    models_dir.mkdir(parents=False, exist_ok=False)

models_dir = models_dir / f"{os.environ['KERAS_BACKEND']}_model.keras"
if models_dir.exists():
    loaded = keras.models.load_model(models_dir)
    loaded.evaluate(test_ds)
    loaded.summary()
else:
    model = generate_model(x_train.shape[1:], 10, os.environ["KERAS_BACKEND"])
    model.summary()
    model.fit(train_dataloader, validation_data=val_dataloader, epochs=3, verbose=1)
    model.save(models_dir)
```

Torch Dataset:

```
import torch
import numpy as np
from typing import Tuple, Any

class ExampleTorchDataset(torch.utils.data.Dataset):
    """
    Custom torch Dataset wrapper for any type of data. This is a simple example
    of how to use Dataset to load a dataset from a list of paths.
    """
    def __init__(self, x: Any, y: Any):
        self.x = x
        self.y = y

    def __len__(self) -> int:
        return len(self.x)

    def __getitem__(self, idx: int) -> Tuple[np.ndarray, np.ndarray]:
        """
        Return x, y for batch idx. Here you can put your custom logic for reading and processing files on the fly
        before to pass it to the model.
        """
        return self.x[idx], self.y[idx]
```

**Comment by sampathweb** [comment]
When you create a PyTorch dataset, its not wrapped inside a `Sequence`.  You can directly use a PyTorch dataset.  I created an example from your code that only has the Torch codepath and everything looks to be working fine.  Can you look at this Gist / Colab and compare?  One change I had to do was use `SparseCategoricalCrossEntropy` Loss since the Target Y were not one hot encoded.

https://gist.github.com/sampathweb/c50899c2175f276d0b5bba98c51fa03b

Let me know if there are any other issues.

**Comment by emi-research-dl** [comment]
Thank you so much!! That was the error!

**Comment by emi-research-dl** [comment]
Hello again @sampathweb, I think it is a bug in Keras import. I am using the Pycharm IDE with the specified requirements for torch CUDA.

If you notice, I think it is importing me the version of Keras that is inside TF.
Imports:
```
import os
# To avoid deadlock in multiprocessing (Keras Core bug)
# Always import first keras
os.environ["KERAS_BACKEND"] = "torch"
import keras
from keras import layers

if os.environ["KERAS_BACKEND"] is not None and os.environ["KERAS_BACKEND"] == "torch":
    import torch
    from Trainers import TorchModel
    # import tensorflow as tf
else:
    import tensorflow as tf
```

Error:

```
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-16 08:46:34.881930: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2.15.0.dev2023092207
2.1.0+cu118
Torch GPU: True
```

Thanks in advanced!

**Comment by SuryanarayanaY** [comment]
Hi @emi-research-dl ,

I think you need to use `import keras_core as keras`. `import keras` will fetch tf-keras package if already installed in the environment. Till the release of **Keras3**, I think we need to use `import keras_core as keras`as  import.

I replicated the same issue without `import keras_core as keras `and the issue resolved with keras_core imported as keras.Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/afc0835487df8e75c6c0aa041b05e0fb/18592.ipynb).

**Comment by emi-research-dl** [comment]
Totally agree @SuryanarayanaY , but this is an error in README. @fchollet is this an error or it is only available in Colab?

![imagen](https://github.com/keras-team/keras/assets/140513018/91fc3ae1-b9fa-4712-a7ec-90438fe6ca0a)

**Comment by SuryanarayanaY** [comment]
Hi @emi-research-dl ,

Raised a PR for the suggested changes to avoid confusion. This shall be valid until Keras3 release.

**Comment by emi-research-dl** [comment]
Hi @SuryanarayanaY,
I think that's not the idea, because if you install Keras from source code, the import is still ``import keras`` not ``import keras_core``. I hope they can provide a solution to this issue, although I think that with the large number of issues Keras 3.0 is going to take some time to be released!
