### ISSUE TITLE
LSTM - different outputs for same weights across CPU and GPU, when using float32 datatype.  Using float64 resolves it.

### ISSUE THREAD

**Issue by lbortolotti** [keras-team/keras#19254]
Hi.  I have an LSTM based-model for which I've noticed quite large discrepancies in prediction when doing inference on CPU or GPU.  The model has been trained with float32 precision throughout.  Enabling float64 at inference-time resolves this CPU/GPU discrepancy.

I have prepared a script to reproduce, that demonstrates the issue (on a slightly smaller scale - it seems my trained model amplifies the issue, while the gist I attach demonstrates it on a freshly-initialised model).

You can find the gist [here](https://gist.github.com/lbortolotti/9fd4022c3eae431120863cf2285edb76).

I'm on TensorFlow+Keras 2.14.0, running in a docker image based on nvidia/cuda:11.8.0-devel-ubuntu22.04

This is the error between GPU and CPU predictions for what should be the same model:
![newplot(29)](https://github.com/keras-team/keras/assets/143824846/e33db617-ec0d-4721-a967-37de280ee24d)

This is the histogram of "layer activity" (cpu_vs_gpu_intermediate_layer_2.html), which I have zoomed in and in which the two instances of the model are clearly different:
![image](https://github.com/keras-team/keras/assets/143824846/dddcbb43-eb20-40a2-b567-5362de00ce4c)

If I uncomment the line
`keras.backend.set_floatx('float64')`

CPU and GPU produce the exact same output, and the "activity histograms" become identical.

Why would CPU and GPU "diverge", and why only in float32?  I'm aware that LSTM has a CUDA-optimized implementation, is it a known issue that this can behave differently to the CPU implementation?

Thanks

**Comment by SuryanarayanaY** [comment]
Hi @lbortolotti ,

There seems some dependencies missing for reproduction of the issue. Could you please look into the gist and suggest?

There will be some precisional difference between CPU and GPU and also  GPU to GPU.Enabling float64 will almost nullify these precisional differences.Also can you compare the difference wrt percentage of the outputs instead of absolute difference and let us know the range?

**Comment by lbortolotti** [comment]
Hi @SuryanarayanaY .

I've fixed the code (it wasn't actually missing dependencies, it was just a __\_\_file____ directive that turns out not to work in a notebook context).

While I was at it, I increased the model size a little, which amplified the numerical differences substantially on my linux box.

You can find a cleaned up notebook [here](https://colab.research.google.com/gist/optiluca/dafd5ac86413fc34906c1d76eb7c0c78/19254.ipynb).

However, in running the notebook, I have seen that the issue does __not__ replicate on colab.

This is the plot of the predictions of a randomly initialised model on colab:
![image](https://github.com/keras-team/keras/assets/143824846/7f14d9cc-2622-45e3-bdf9-4250f0a0852d)

The exact same code you find on colab, run on my linux box with an nvidia GPU, results in the following plot:
![image](https://github.com/keras-team/keras/assets/143824846/960d1a17-d9bb-4f83-a326-c468cc0ec8a8)

I'm now running TF 2.15 on my linux box, so the TF version is the same that is running on colab.

At this point I'd be inclined to think there's something amiss on the CUDA/nvidia side of things.

On prem I am running CUDA12.2, CuDNN 8904, on an A100, with the following cuda package versions (as pulled in by tensorflow[and-cuda])

nvidia-cublas-cu12==12.2.5.6      
nvidia-cuda-cupti-cu12==12.2.142  
nvidia-cuda-nvcc-cu12==12.2.140   
nvidia-cuda-nvrtc-cu12==12.2.140  
nvidia-cuda-runtime-cu12==12.2.140
nvidia-cudnn-cu12==8.9.4.25       
nvidia-cufft-cu12==11.0.8.103     
nvidia-curand-cu12==10.3.3.141    
nvidia-cusolver-cu12==11.5.2.141  
nvidia-cusparse-cu12==12.1.2.141  
nvidia-nccl-cu12==2.16.5          
nvidia-nvjitlink-cu12==12.2.140 

Any ideas?  Ideally I'd want to try and set up my own "vanilla" colab environment, and install tensorflow[and-cuda] myself to try the same stack there as well.  However I've already run out of my GPU usage quota, so haven't managed to try myself.

**Comment by SuryanarayanaY** [comment]
Hi @lbortolotti ,

I have replicated the reported error with keras2 and attached gist [here](https://colab.sandbox.google.com/gist/SuryanarayanaY/b7ed5fed5780d18f0a507ff5bb42f43c/19254_keras2.ipynb).

Could you please confirm whether this is issue with Keras3. If not an issue with Keras3 then it needs to be reported at [tf_keras](https://github.com/keras-team/tf-keras/issues) repo. Thanks!

**Comment by lbortolotti** [comment]
> Hi @lbortolotti ,
> 
> I have replicated the reported error with keras2 and attached gist [here](https://colab.sandbox.google.com/gist/SuryanarayanaY/b7ed5fed5780d18f0a507ff5bb42f43c/19254_keras2.ipynb).
> 
> Could you please confirm whether this is issue with Keras3. If not an issue with Keras3 then it needs to be reported at [tf_keras](https://github.com/keras-team/tf-keras/issues) repo. Thanks!

The linked gist does *not* seem like it replicates the error?  The difference in output between CPU and GPU inference is negligible, much smaller than what I am seeing on-prem.

on-prem
![310431472-960d1a17-d9bb-4f83-a326-c468cc0ec8a8](https://github.com/keras-team/keras/assets/143824846/b02df382-ab53-4601-bad4-29c5c38af600)

gist
![immagine](https://github.com/keras-team/keras/assets/143824846/95d5e661-2e80-4f19-a23f-903618eebbe9)

I'd be very happy if the gist replicated, but it doesn't seem to?  Or am I missing something?

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @lbortolotti ,

Yeah I noticed now the plot for CPU is missing in the gist. But the CPU-GPU diff value showing the difference though which I have seen and confirmed as difference.

The code is not compatible for keras3. If the issue can be replicable with Keras3 please report with the modified code snippet. Else please report it at tf_keras repo . Thanks!

**Comment by SuryanarayanaY** [comment]
> * The issue disappears with keras3
> * The issue still occurs with tf-keras 2.16.0

Please note if the issue is with `tf-keras` package then the issue is with Keras2 code which needs to be addressed at tf-keras [repo](https://github.com/keras-team/tf-keras/issues). 

If you have switched to TF2.16v then by default tf.keras points to Keras3 and if TF2.16v resolves your issue then probably we can mark it resolved here.If the issue not replicable with Keras3 then please report the issue at tf-keras.

**Comment by lbortolotti** [comment]
OK, I'll reopen in tf-keras, and hope can get to the bottom of it there.  Thanks!
