### ISSUE TITLE
Data parallelism with multiple GPUs with fit_generator

### ISSUE THREAD

**Issue by genghis88** [keras-team/keras#7698]
Has anyone achieved data parallelism with multiple GPUs while training large datasets with fit_generator?

**Comment by CeadeS** [comment]
Are you looking for something like this? [https://github.com/kuza55/keras-extras/blob/master/utils/multi_gpu.py](https://github.com/kuza55/keras-extras/blob/master/utils/multi_gpu.py )

**Comment by genghis88** [comment]
@CeadeS I've tried this. This one too: https://gist.github.com/vvpreetham/1379cc4e208ea33ce3e615067e92fc5e. I have 4 GPUs, but I am unable to use 4 times the batch size because it goes out of memory. Wanted to know how to make data parallelism work with fit_generator. Check out https://github.com/fchollet/keras/issues/2436 where **jonilaserson** gives a method similar to the one in the link you provided and says it should work with fit and predict only.

**Comment by CeadeS** [comment]
@genghis88 many People would be happy with built in parallelism in keras. But it is not implemented yet. What is that maximum batchsize with and without parallel data in your case? There is some overhead when using multiple GPU and therefore the batchsize is not increasing linearly.  I think i tried fit generator in the past and it worked in my case. Note that some architectures are not good with data parallelism.

**Comment by genghis88** [comment]
@CeadeS 1024 is the largest batch_size I can use on one GPU. This doesn't change with make_parallel. I understand that there is an overhead of averaging gradients, etc and therefore multiple GPUs cannot scale linearly in terms of time, but what exactly is the overhead in terms of space for multiple GPUs to not scale linearly (in batch_size)?
Oh that is awesome! Did you use the exact function in the link you gave me?

**Comment by CeadeS** [comment]
@genghis88 yes i tried exactly this Code. But i never used so big batch sizes. Since i worked with inception v4 and inception resnet v2 my batch sizes where 4 * 50 and 4 * 20. I utilized 4 Titan X for that. I only made a small change to the code for saving the model.

**Comment by genghis88** [comment]
@CeadeS Aah I see. The problem with my data is that with a batch size of 1024, it takes 1h 20min per epoch to train on one GPU. That's the reason I am trying to use 4. I was actually able to use 4 GPUs and reduce training time to ~35 min per epoch using keras with MXNet backend, but the program and machine crash after one epoch. Thank you for the help! 👍 Trying to write plain tensorflow code to use multiple GPUs.

**Comment by DBlackKat** [comment]
@genghis88  May i know which repository you used for mxnet keras?  I was having trouble setting up MXNet keras as well.

**Comment by nbansal90** [comment]
@genghis88 Did you find any solution this issue. Actually I am also getting this error, while using multiple callbacks in a multi_gpu scenario, while using fit_generator. Struggling with this problem for quite some time now :) Hoping to find a solution.Would be glad to hear back from you!

**Comment by rawmean** [comment]
I get a shape mismatch error unless I set the batch size in the generator to the number of GPUs (which doesn't make sense).
I thought if the batch size is `B`, the generator should generate batches of size `B/num_GPUs` because multi-gpu divides the batch into sub-batches and expects each replica of the model to process a sub-batch.  Is that correct?
